version: '3.8'

services:
  web:
    hostname: docker
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash ./docker_conf/launch.sh
    env_file: ./docker_conf/.dev.env
    volumes:
      - .:/home/django/app
    ports:
      - 8000:8000
      - 80:80
      - 22:22
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    volumes:
      - .:/mnt/django_app
    env_file: ./docker_conf/.dev.env
    shm_size: 2g
    ports:
      - 5432:5432

  cache:
    image: redis:7.0.9-bullseye
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes: 
      - redis_data:/data

volumes:
  redis_data:
  pgadmin_data:
