"""
Django settings for helmetbot project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@*#jqr8mkdvxx^gog!0h41$(t23(vxurn5-!)tsklc!gn14=_*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'quotationbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helmetbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'quotationbot.settings_context_processor.chat_server_settings_context',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'helmetbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": "TestDB",
        "USER": "django",
        "PASSWORD": "IdiotChatbotPassword123456789",
        "HOST": "db",
        "PORT": "5432",
        'CONN_MAX_AGE': 60,
    },

}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


TWITCH_IRC_ADDRESS = 'irc.chat.twitch.tv'
TWITCH_IRC_PORT = 6667
TWITCH_HANDLE = 'your_twitch_user_name'
TWITCH_OAUTH_TOKEN = 'go here to get an oauth token: https://antiscuff.com/oauth/'
TWITCH_IRC_MAX_LENGTH = 500 #this length probably needs to be tested
TWITCH_UPTIME_URL = 'https://decapi.me/twitch/uptime/'

#infrequent defaults
BOT_MINIMUM_WAIT_MINUTES = 60 # default min for a channel
BOT_MAXIMUM_WAIT_MINUTES = 120 # default max for a channel
BOT_DEFAULT_BUCKETS = ['wizdum'] #default buckets to split your quotes into
QUOTE_DEFAULT_BUCKET_NAME = BOT_DEFAULT_BUCKETS[0]
QUOTATION_TIME_INTERVAL = 5 * 60 #five minutes downtime in between runs. 
BOT_IGNORE_ERRORS = False # when enabled the bot will ignore runtime exceptions when it can

IMESSAGE_SERVICE_URL = 'http://127.0.0.1:1337/message'
IMESSAGE_BEDTIME_HOUR = 21
IMESSAGE_WAKING_HOUR = 10

#default 10 minute uptime before channel considered 'live'
MINIMUM_CHANNEL_UPTIME_SECONDS = 10 * 60
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfilesdir')    

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
try:
    from .local_settings import *
except ImportError as e:
    print(e)
