# Generated by Django 4.1.2 on 2022-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bot_maximum_minutes',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bot_minimum_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='channel',
            name='enabled_buckets',
            field=models.TextField(default='wizdum\n'),
        ),
    ]
