# Generated by Django 4.1.2 on 2022-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationbot', '0002_alter_channel_bot_maximum_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_run_at', models.DateTimeField()),
                ('twitch_irc_address', models.CharField(default='irc.chat.twitch.tv', max_length=500)),
                ('twitch_irc_port', models.CharField(default=6667, max_length=500)),
                ('twitch_handle', models.CharField(default='your_twitch_user_name', max_length=500)),
                ('twitch_oauth_token', models.CharField(default='go here to get an oauth token: https://twitchapps.com/tmi/', max_length=1000)),
                ('chat_server_delay_seconds', models.IntegerField(default=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
