# Generated by Django 4.1.2 on 2022-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationbot', '0003_chatserversettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatserversettings',
            name='next_run_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='bucket_name',
            field=models.CharField(default='wizdum', max_length=100),
        ),
    ]
