# Generated by Django 4.1.2 on 2022-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationbot', '0004_alter_chatserversettings_next_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_needy_gf_channel',
            field=models.BooleanField(default=False),
        ),
    ]
