# Generated by Django 4.1.2 on 2022-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationbot', '0005_channel_is_needy_gf_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatserversettings',
            options={'verbose_name_plural': 'Chat server settings'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='is_needy_gf_channel',
            new_name='is_imessage_server',
        ),
        migrations.AlterField(
            model_name='channel',
            name='enabled_buckets',
            field=models.TextField(default='manda\n'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='bucket_name',
            field=models.CharField(default='manda', max_length=100),
        ),
    ]
